### ISSUE TITLE
NBC.com plugin for Serviio

### ISSUE THREAD

**Issue by randompup** [randompup/ServiioNBC#1]
Can anyone develop a Web Resource plugin for Serviio (Groovy based). The specifications are given here:
http://www.serviio.org/index.php?option=com_content&view=article&id=42#plugins
http://forum.serviio.org/viewtopic.php?f=22&t=3274

A sample CBS.com plugin is available here:
http://forum.serviio.org/viewtopic.php?f=20&t=5401

Once the user enters the URL in Serviio, e.g.:
http://www.nbc.com/heroes-reborn/episodes

The plugin should parse the URL and extract the list of the full episodes available to play on the website and return them along with the playable media URL to Serviio

**Comment by hunnypuppy** [comment]
Will not be fixed

**Comment by randompup** [comment]
Will not be fixed
